steps:

steps:

- id: 'Contruindo imagem'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'main']
  env: ['GOPATH=$PWD .']

# - id: 'Rodando os testes'
#   name: 'gcr.io/cloud-builders/go'
#   args: ['test', '-v','main']
#   env: ['GOPATH=.']
#
#
# - id: 'Build imagem server e push'
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '--tag=gcr.io/$PROJECT_ID/goserver', '.']
#
# images: ['gcr.io/$PROJECT_ID/goserver']

# - id: 'Constuindo a imagem de teste'
#   name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'docker image build --target build --tag go-hpa:test .']

# - id: 'Instalando o app go-hpa'
#   name: 'gcr.io/cloud-builders/go'
#   args: ['install', 'go-hpa']
#   env: ['GOPATH=.']
#
# - id: 'Executando Teste Unitário'
#   name: 'gcr.io/cloud-builders/go'
#   args: ['test', '-v','./...']
#   env: ['GOPATH=.']
#
# - id: 'Fazendo o Push da Imagem para o Cloud Registry'
#   name: 'gcr.io/cloud-builders/docker'
#   args:
#     - 'build'
#     - '-t'
#     - 'gcr.io/$PROJECT_ID/go-hpa:latest'
#     - '.'
#
# images: ['gcr.io/$PROJECT_ID/go-hpa:latest']
