steps:

steps:

- id: 'Instalando dependencias'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'app']

- id: 'Rodando os Testes Unitários'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v','app']

- id: 'Build e push da Imagem'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/go-hpa:$COMMIT_SHA', '.']

images: ['gcr.io/$PROJECT_ID/go-hpa:$COMMIT_SHA']
