steps:

- id: 'Instalando o app go-hpa'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'go-hpa']
  env: ['GOPATH=.']

- id: 'Executando Teste Unitário'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v','./...']
  env: ['GOPATH=.']

# - id: 'Fazendo o Push da Imagem para o Cloud Registry'
#   name: 'gcr.io/cloud-builders/docker'
#   args:
#     - 'build'
#     - '-t'
#     - 'gcr.io/$PROJECT_ID/go-hpa:latest'
#     - '.'
#
# images: ['gcr.io/$PROJECT_ID/go-hpa:latest']
