steps:

steps:

- id: 'Contruindo imagem'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'sqrt']

- id: 'Rodando os Testes Unitários'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v','sqrt']

- id: 'Build e push da Imagem'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/go-hpa', '.']

images: ['gcr.io/$PROJECT_ID/go-hpa:latest']
