apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-hpa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
      - name: go-hpa
        image: fbrz/go-hpa
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "50m"
