FROM golang:1.11-alpine AS build

RUN apk add --update --no-cache gcc git build-base

WORKDIR /go/src/sqrt
ADD ./src /go/src/sqrt

RUN CGO_ENABLED=0 go build -o /bin/sqrt

FROM scratch
COPY --from=build /bin/demo /bin/sqrt

EXPOSE 80

WORKDIR /go/src/sqrt
ENTRYPOINT ["/bin/sqrt"]
