FROM golang:1.11-alpine
RUN apk add --update --no-cache gcc git build-base

#FROM golang:onbuild

WORKDIR /go/src/app
ADD ./src/app /go/src/app
# COPY main*.go go.* /go/src/app
RUN CGO_ENABLED=0 go build -o /bin/app

EXPOSE 8000

#CMD ["go", "test", "-v"]
CMD ["go", "run", "main.go"]

#CMD["./main"]
#ENTRYPOINT ["./main"]
