FROM golang:1.11-alpine AS build
RUN apk add --update --no-cache gcc git build-base

ADD ./src /go/src

WORKDIR /go/src/sqrt
RUN CGO_ENABLED=0 go build -o /bin/sqrt

FROM scratch
WORKDIR /go/src/sqrt

COPY --from=build /bin/sqrt /bin/sqrt

EXPOSE 80

ENTRYPOINT ["/bin/sqrt"]
